# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a9ee0e8e498f1f1fb59b08b9ee93664b4a17360a48d296969cbc9f97095c2b8ee819bfeb5a794d1b3deda75bb168ca14a92f4955bbd8c18835928b4d61ae9e

test:
  secret_key_base: 792c58f60311979ba8937f561c0150ade69c2ad561824ac8a12134fcd0731ea2052f5fb29f318936dad3dabcfa3a371da26f920f45b04c7838e465494405f324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
